### ISSUE TITLE
Dependency on django-grapelli

### ISSUE THREAD

**Issue by stevejalim** [ninapavlich/django-ace-overlay#1]
Been trying to get this running in a plain Django 1.9 admin, but hitting this

```
ReferenceError: Can't find variable: grp
```

which looks like it's [this line in widget.js](https://github.com/ninapavlich/django-ace-overlay/blob/master/ace_overlay/static/ace_overlay/widget.js#L3)

```
    $ = grp.jQuery;
```

I couldn't find anything that noted django-grapelli as a requirement -- did I miss something? If not, it'd be handy to note this in the README.

Cheers!
Steve

**Comment by ninapavlich** [comment]
Thanks for the note! I'll update that to work without grappelli; it shouldn't really be a requirement!

Nina

**Comment by stevejalim** [comment]
No worries - have just sent you a PR which should take care of it!

Cheers
S

**Comment by stevejalim** [comment]
Thanks for merging the PR - could you let me know if/when you get a chance to update the PyPi package?

Cheers!
Steve

**Comment by ninapavlich** [comment]
Oops, I completely forgot -- thanks for reminding me!

That's updated to version 0.5.

Thanks!
